---
- hosts: all
  become: yes

  vars:
    disabled_filesystems:
      - cramfs
      - freevxfs
      - jffs2
      - hfs
      - hfsplus
      - squashfs
      - udf
      - vfat
  
  tasks:
    - name: enable automatic logout after 5 minutes
      blockinfile:
        path: /etc/profile
        block: |
          TMOUT=300
          readonly TMOUT
          export TMOUT
          readonly HISTFILE

    - name: disable interactive startup
      blockinfile:
        path: /etc/sysconfig/init
        block: |
          # Disable Interactive Startup
          PROMPT=no
          # Force sulogin for single user mode
          SINGLE=/sbin/sulogin

    - name: restrict root login to console only
      lineinfile:
        path: /etc/securetty
        line: tty1

    - name: ensure /root home has correct permissions
      file:
        path: /root
        mode: 0700

    - name: Ensure auditd is configured to keep_logs
      lineinfile:
        path: /etc/audit/auditd.conf
        regexp: '^max_log_file_action'
        line: 'max_log_file_action = keep_logs'

    - name: disable unused filesystems
      template:
        src: modprobe.j2
        dest: /etc/modprobe.d/dev-sec.conf
        mode: 0400
                
    - name: /etc/login.defs should not be writable
      file:
        path: /etc/login.defs
        mode: 0400

    - name: ICMP ratelimit
      sysctl:
        name: net.ipv4.icmp_ratelimit
        value: 100

    - name: ICMP ratemask
      sysctl:
        name: net.ipv4.icmp_ratemask
        value: 88089

    - name: TCP timestamps
      sysctl:
        name: net.ipv4.tcp_timestamps
        value: 0

    - name: ARP ignore
      sysctl:
        name: net.ipv4.conf.all.arp_ignore
        value: 1

    - name: ARP announce
      sysctl:
        name: net.ipv4.conf.all.arp_announce
        value: 2

    - name: TCP RFC1337 Protect Against TCP Time-Wait
      sysctl:
        name: net.ipv4.tcp_rfc1337
        value: 1

    - name: Disable acceptance of all IPv4 redirected packets (1 of 2)
      sysctl:
        name: net.ipv4.conf.default.accept_redirects
        value: 0

    - name: Disable acceptance of all IPv4 redirected packets (2 of 2)
      sysctl:
        name: net.ipv4.conf.all.accept_redirects
        value: 0
